export const entities = {
    users: 'users',
    roles: 'roles',
    applications: 'applications',
    organizations: 'organizations',
    conditions: 'conditions',
    categories: 'categories',
    customers: 'customers',
    products: 'products',
    suppliers: 'suppliers',
    types: 'types',
    groups: 'groups',
    status: 'status',
    units: 'units',
    contracts: 'contracts',
    contractTypes: 'contractTypes',
    contractStatus: 'contractStatus',
    contractEventTypes: 'contractEventTypes',
    contractInfos: 'contractInfos',

}